model:
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 8192
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_start: 0
        disc_conditional: false
        disc_in_channels: 3
        codebook_weight: 1.0
        perceptual_weight: 1.0
        disc_weight: 0.8
