# Model parameters
input_channels: 3
output_channels: 1
image_size: 512
hidden_dim: 256
num_residual_layers: 2
dropout: 0.1

# Training parameters
batch_size: 16
learning_rate: 0.0001
num_epochs: 100
device: "cuda"  # "cuda" or "cpu"

# Data paths (update these to your actual paths)
input_path: "AR_RM_backup/ICASSP2025_Dataset/Inputs/Task_1_ICASSP"
output_path: "AR_RM_backup/ICASSP2025_Dataset/Outputs/Task_1_ICASSP"

# Output directories
checkpoint_dir: "./checkpoints"
log_dir: "./logs"
results_dir: "./results"

# Data augmentation
augmentation_preset: "vqgan"  # Options: "light", "medium", "heavy", "vqgan"

# Data splits
train_split: 0.8
val_split: 0.1
test_split: 0.1

# Data loading
num_workers: 4

# Training schedule
save_every: 10        # Save checkpoint every N epochs
validate_every: 5     # Validate every N epochs

# Dataset parameters
buildings: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
antennas: [1]
frequencies: [1]
samples_per_config: 50
